
package Vista;


import Modelo.BD.cConexion;

import Vista.Paneles.Camioneros;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Modelo.CambiaPanel;
import Vista.Paneles.Camiones;

import Vista.Paneles.MenuPrincipal;
import Vista.Paneles.Paquetes;
import Vista.Paneles.Provincias;
import javax.swing.JPanel;

/**
 *
 * @author roy-j
 */
public class Menu extends javax.swing.JFrame {

    /*
    public static final Vehiculo vehiculo = new Vehiculo();
    public final AsignarEspacios asignarEspacios = new AsignarEspacios();
    public static ControladorAsignacion objControlador;

    public static final cConexion objconexion = new cConexion();
    */
    public Menu() {
        
        MenuPrincipal menup = new MenuPrincipal();
       // asignarEspacios.CargarDatos();
        
        initComponents();
        cambiarPanel( menup.getJpanel());
        imagenes();
        this.setLocationRelativeTo(null);
    }
    
    public  void cambiarPanel(JPanel nuevoPanel) {
        new CambiaPanel(PanelPrincipal, nuevoPanel);
    }

    public final void imagenes() {

        //Logo
        ImageIcon icono = new ImageIcon(getClass().getResource("/Recursos/Imagenes/Icon2.png"));
        Icon marco = new ImageIcon(icono.getImage().getScaledInstance(IconLabel.getWidth(), IconLabel.getHeight(), Image.SCALE_DEFAULT));
        IconLabel.setIcon(marco);
        //Person
        ImageIcon iconoPersona = new ImageIcon(getClass().getResource("/Recursos/Imagenes/Persona.png"));
        Icon Person = new ImageIcon(iconoPersona.getImage().getScaledInstance(IconPerson.getWidth(), IconPerson.getHeight(), Image.SCALE_DEFAULT));
        IconPerson.setIcon(Person);
        //Cono
        ImageIcon cono = new ImageIcon(getClass().getResource("/Recursos/Imagenes/cono.png"));
        Icon IconoCono = new ImageIcon(cono.getImage().getScaledInstance(Cono.getWidth(), Cono.getHeight(), Image.SCALE_DEFAULT));
        Cono.setIcon(IconoCono);
        Cono2.setIcon(IconoCono);
        Cono1.setIcon(IconoCono);
        Cono3.setIcon(IconoCono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IconLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        IconPerson = new javax.swing.JLabel();
        Cono = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Camioneros = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cono2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Camiones = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        Cono1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Paquetes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cono3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Provincias = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Cono4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Rutas = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(IconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 1320, 10));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        jLabel1.setText("Administrador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 60, 150, -1));
        jPanel1.add(IconPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 100, 90));
        jPanel1.add(Cono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 60, 80));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        Camioneros.setBackground(new java.awt.Color(204, 204, 204));
        Camioneros.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        Camioneros.setText("Camioneros");
        Camioneros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Camioneros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CamionerosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CamionerosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(Camioneros, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Camioneros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 240, 40));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel3.setText("Informes");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 180, 40));
        jPanel1.add(Cono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 60, 80));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        Camiones.setBackground(new java.awt.Color(204, 204, 204));
        Camiones.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        Camiones.setText("Camiones");
        Camiones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Camiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CamionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(Camiones, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Camiones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 240, 40));

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setLayout(new javax.swing.BoxLayout(PanelPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 1020, 620));
        jPanel1.add(Cono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 60, 80));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        Paquetes.setBackground(new java.awt.Color(204, 204, 204));
        Paquetes.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        Paquetes.setText("Paquetes");
        Paquetes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Paquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaquetesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(Paquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Paquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 240, 40));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel6.setText("Informes");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 180, 40));
        jPanel1.add(Cono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 60, 80));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        Provincias.setBackground(new java.awt.Color(204, 204, 204));
        Provincias.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        Provincias.setText("Provincias");
        Provincias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Provincias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProvinciasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(Provincias, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Provincias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 240, 40));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel8.setText("Informes");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 180, 40));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 2, 48)); // NOI18N
        jLabel9.setText("BIENVENIDO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 400, -1));
        jPanel1.add(Cono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 60, 80));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        Rutas.setBackground(new java.awt.Color(204, 204, 204));
        Rutas.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        Rutas.setText("Rutas");
        Rutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RutasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(Rutas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Rutas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 240, 40));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel10.setText("Informes");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void CamionerosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CamionerosMousePressed
       

    }//GEN-LAST:event_CamionerosMousePressed

    private void PaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaquetesMouseClicked
        Paquetes pq = new Paquetes();
       cambiarPanel(pq.getJpanel());
    }//GEN-LAST:event_PaquetesMouseClicked

    private void CamionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CamionesMouseClicked
        Camiones camiones = new Camiones();
        cambiarPanel( camiones.getJpanel());
    }//GEN-LAST:event_CamionesMouseClicked

    private void CamionerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CamionerosMouseClicked
        Camioneros asingacion = new Camioneros();
       cambiarPanel(asingacion.getJpanel());
    }//GEN-LAST:event_CamionerosMouseClicked

    private void ProvinciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProvinciasMouseClicked
      Provincias asingacion = new Provincias();
       cambiarPanel(asingacion.getJpanel());
    }//GEN-LAST:event_ProvinciasMouseClicked

    private void RutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RutasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RutasMouseClicked
    public JPanel getJpanel() {
        return PanelPrincipal;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Camioneros;
    public static javax.swing.JLabel Camiones;
    private javax.swing.JLabel Cono;
    private javax.swing.JLabel Cono1;
    private javax.swing.JLabel Cono2;
    private javax.swing.JLabel Cono3;
    private javax.swing.JLabel Cono4;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JLabel IconPerson;
    public static javax.swing.JPanel PanelPrincipal;
    public static javax.swing.JLabel Paquetes;
    public static javax.swing.JLabel Provincias;
    public static javax.swing.JLabel Rutas;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
