
package Vista.Paneles;


import Controlador.ControladorAsignarCamion;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author roy-j
 */
public class AsignarCamion extends javax.swing.JFrame {
    
    

    public AsignarCamion() {
        initComponents();
        ControladorAsignarCamion cm = new ControladorAsignarCamion(AsignarCamion.this) ; 
        cm.consultarCambioneroNombre(jCamioneros);
        cm.consultarCamionMatricula(jCamiones);
        cm.listar(Tabla);
        Observaciones.setVisible(false);
        jLabel6.setVisible(false);

    }
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Asignacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Consultar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        finalizarUso = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCamioneros = new javax.swing.JComboBox<>();
        jCamiones = new javax.swing.JComboBox<>();
        Eliminar2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        inputCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Observaciones = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Asignacion.setBackground(new java.awt.Color(255, 255, 255));
        Asignacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/car.png"))); // NOI18N
        Asignacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 137, 152));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel4.setText("Codigo");
        Asignacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        Asignacion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1020, 26));

        Consultar.setBackground(new java.awt.Color(181, 223, 224));
        Consultar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Consultar.setText("Consultar");
        Consultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarMouseClicked(evt);
            }
        });
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        Asignacion.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 160, 30));

        Crear.setBackground(new java.awt.Color(181, 223, 224));
        Crear.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Crear.setText("Crear");
        Crear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        Asignacion.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 160, 30));

        Actualizar.setBackground(new java.awt.Color(181, 223, 224));
        Actualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        Asignacion.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, 160, 30));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel6.setText("Ingresa las Observaciones");
        Asignacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 210, 20));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel11.setText("Asignacion de Camiones a Camioneros");
        Asignacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 560, 40));

        finalizarUso.setBackground(new java.awt.Color(181, 223, 224));
        finalizarUso.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        finalizarUso.setText("Finalizar Uso");
        finalizarUso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        finalizarUso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finalizarUsoMouseClicked(evt);
            }
        });
        finalizarUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarUsoActionPerformed(evt);
            }
        });
        Asignacion.add(finalizarUso, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 160, 30));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla);

        Asignacion.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 600, 220));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel12.setText("Ingrese los siguientes Datos");
        Asignacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 350, 40));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel13.setText("Tabla de Asignaciones");
        Asignacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 160, 40));

        Asignacion.add(jCamioneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 240, 30));

        Asignacion.add(jCamiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 240, 30));

        Eliminar2.setBackground(new java.awt.Color(181, 223, 224));
        Eliminar2.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Eliminar2.setText("Eliminar");
        Eliminar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar2MouseClicked(evt);
            }
        });
        Eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar2ActionPerformed(evt);
            }
        });
        Asignacion.add(Eliminar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, 160, 30));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel5.setText("Selecciona el Camionero");
        Asignacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 210, 20));

        inputCodigo.setEditable(false);
        inputCodigo.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(inputCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setText("Selecciona el Camion");
        Asignacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, 20));

        Observaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObservacionesActionPerformed(evt);
            }
        });
        Asignacion.add(Observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarMouseClicked
       ControladorAsignarCamion cm = new ControladorAsignarCamion(AsignarCamion.this) ; 
       cm.consultarCamioneros(Tabla);
    }//GEN-LAST:event_ConsultarMouseClicked

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_ConsultarActionPerformed

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
     ControladorAsignarCamion cm = new ControladorAsignarCamion(AsignarCamion.this) ; 
        cm.crearAsignacionCamionaCamionero();
        cm.listar(Tabla);
    }//GEN-LAST:event_CrearMouseClicked

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_CrearActionPerformed

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked
       ControladorAsignarCamion cm = new ControladorAsignarCamion(AsignarCamion.this) ; 
       cm.actualizarAsignacion();
        cm.listar(Tabla);
         Observaciones.setVisible(false);
        jLabel6.setVisible(false);
    }//GEN-LAST:event_ActualizarMouseClicked

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
      
    }//GEN-LAST:event_ActualizarActionPerformed

    private void finalizarUsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalizarUsoMouseClicked
        // TODO add your handling code here:
        ControladorAsignarCamion cm = new ControladorAsignarCamion(AsignarCamion.this) ; 
        Observaciones.setVisible(true);
        jLabel6.setVisible(true);
        cm.listar(Tabla);
    }//GEN-LAST:event_finalizarUsoMouseClicked

    private void finalizarUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalizarUsoActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        
        int fila = Tabla.getSelectedRow();
        inputCodigo.setText(Tabla.getValueAt(fila, 0).toString());
        jCamioneros.setSelectedItem(Tabla.getValueAt(fila, 1).toString());
        jCamiones.setSelectedItem((String) Tabla.getValueAt(fila, 2));
       
    }//GEN-LAST:event_TablaMouseClicked

    private void Eliminar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar2MouseClicked

    private void Eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar2ActionPerformed

    private void ObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObservacionesActionPerformed

    public JPanel getJpanel(){
        return Asignacion;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarCamion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarCamion().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Actualizar;
    public static javax.swing.JPanel Asignacion;
    public static javax.swing.JButton Consultar;
    public static javax.swing.JButton Crear;
    public static javax.swing.JButton Eliminar2;
    public javax.swing.JTextField Observaciones;
    public javax.swing.JTable Tabla;
    public static javax.swing.JButton finalizarUso;
    public javax.swing.JTextField inputCodigo;
    public javax.swing.JComboBox<String> jCamioneros;
    public javax.swing.JComboBox<String> jCamiones;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
