
package Vista.Paneles;


import Controlador.ControladorCamioneros;
import Modelo.CambiaPanel;
import Modelo.entidades.Camionero;
import Vista.Menu;
import static Vista.Menu.PanelPrincipal;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author roy-j
 */
public class Camioneros extends javax.swing.JFrame {
    
    

    public Camioneros() {
        initComponents();
        ControladorCamioneros cm = new ControladorCamioneros(Camioneros.this) ; 
        cm.listar(Tabla);

    }
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
     public  void cambiarPanel(JPanel nuevoPanel) {
        new CambiaPanel(PanelPrincipal, nuevoPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Asignacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        inputCedula = new javax.swing.JTextField();
        Consultar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Asignar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        inputNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        inputTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        inputDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        inputSalario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        inputPoblacion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Eliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Asignacion.setBackground(new java.awt.Color(255, 255, 255));
        Asignacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/car.png"))); // NOI18N
        Asignacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 137, 152));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel4.setText("Cedula");
        Asignacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        Asignacion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1020, 26));

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 250, 20));

        inputCedula.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputCedula.setToolTipText("");
        inputCedula.setBorder(null);
        inputCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputCedulaMousePressed(evt);
            }
        });
        inputCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCedulaActionPerformed(evt);
            }
        });
        Asignacion.add(inputCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 270, 30));

        Consultar.setBackground(new java.awt.Color(181, 223, 224));
        Consultar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Consultar.setText("Consultar");
        Consultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarMouseClicked(evt);
            }
        });
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        Asignacion.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 160, 30));

        Crear.setBackground(new java.awt.Color(181, 223, 224));
        Crear.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Crear.setText("Crear");
        Crear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        Asignacion.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 160, 30));

        Actualizar.setBackground(new java.awt.Color(181, 223, 224));
        Actualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        Asignacion.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 160, 30));

        Asignar.setBackground(new java.awt.Color(181, 223, 224));
        Asignar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Asignar.setText("Asignar Camion");
        Asignar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Asignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AsignarMouseClicked(evt);
            }
        });
        Asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarActionPerformed(evt);
            }
        });
        Asignacion.add(Asignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 160, 30));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel5.setText("Datos Personales");
        Asignacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 220, 40));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel6.setText("Nombre");
        Asignacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 20));

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, 20));

        inputNombre.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputNombre.setToolTipText("");
        inputNombre.setBorder(null);
        inputNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputNombreMousePressed(evt);
            }
        });
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        Asignacion.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 270, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setText("Telefono");
        Asignacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 210, 20));

        jSeparator7.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 250, 20));

        inputTelefono.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputTelefono.setToolTipText("");
        inputTelefono.setBorder(null);
        inputTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputTelefonoMousePressed(evt);
            }
        });
        inputTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefonoActionPerformed(evt);
            }
        });
        Asignacion.add(inputTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 270, 30));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel8.setText("Direccion");
        Asignacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 210, 20));

        jSeparator8.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 250, 20));

        inputDireccion.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputDireccion.setToolTipText("");
        inputDireccion.setBorder(null);
        inputDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputDireccionMousePressed(evt);
            }
        });
        inputDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDireccionActionPerformed(evt);
            }
        });
        Asignacion.add(inputDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 270, 30));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel9.setText("Salario");
        Asignacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 210, 20));

        jSeparator9.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 250, 20));

        inputSalario.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputSalario.setToolTipText("");
        inputSalario.setBorder(null);
        inputSalario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputSalarioMousePressed(evt);
            }
        });
        inputSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSalarioActionPerformed(evt);
            }
        });
        Asignacion.add(inputSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 270, 30));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel10.setText("Poblacion");
        Asignacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 210, 20));

        jSeparator10.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 250, 20));

        inputPoblacion.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputPoblacion.setToolTipText("");
        inputPoblacion.setBorder(null);
        inputPoblacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputPoblacionMousePressed(evt);
            }
        });
        inputPoblacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPoblacionActionPerformed(evt);
            }
        });
        Asignacion.add(inputPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 270, 30));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel11.setText("Administracion de Camioneros");
        Asignacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 560, 40));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        Asignacion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 650, 330));

        Eliminar1.setBackground(new java.awt.Color(181, 223, 224));
        Eliminar1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Eliminar1.setText("Eliminar");
        Eliminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar1MouseClicked(evt);
            }
        });
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });
        Asignacion.add(Eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Asignacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputCedulaMousePressed
        if(inputCedula.getText().equals("Placa")){
            inputCedula.setText("");
            inputCedula.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_inputCedulaMousePressed

    private void inputCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCedulaActionPerformed

    private void ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarMouseClicked
        ControladorCamioneros cm = new ControladorCamioneros(Camioneros.this) ; 
       cm.consultarCamioneros(Tabla);
       
    }//GEN-LAST:event_ConsultarMouseClicked

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_ConsultarActionPerformed

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
      ControladorCamioneros cm = new ControladorCamioneros(Camioneros.this) ; 
       cm.crearCamionero();
       cm.listar(Tabla);
        
    }//GEN-LAST:event_CrearMouseClicked

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_CrearActionPerformed

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked

ControladorCamioneros cm = new ControladorCamioneros(Camioneros.this) ; 
       cm.actualizarCamionero();
       cm.listar(Tabla);
    }//GEN-LAST:event_ActualizarMouseClicked

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
      
    }//GEN-LAST:event_ActualizarActionPerformed

    private void AsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AsignarMouseClicked
          AsignarCamion asgcam = new AsignarCamion();
    cambiarPanel( asgcam.getJpanel());
       
    }//GEN-LAST:event_AsignarMouseClicked

    private void AsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsignarActionPerformed

    private void inputNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputNombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreMousePressed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputTelefonoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefonoMousePressed

    private void inputTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefonoActionPerformed

    private void inputDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDireccionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDireccionMousePressed

    private void inputDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDireccionActionPerformed

    private void inputSalarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSalarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSalarioMousePressed

    private void inputSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSalarioActionPerformed

    private void inputPoblacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPoblacionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPoblacionMousePressed

    private void inputPoblacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPoblacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPoblacionActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
 
        inputCedula.setText(Tabla.getValueAt(fila, 0).toString());
        inputNombre.setText((String) Tabla.getValueAt(fila, 1));
        inputTelefono.setText((String) Tabla.getValueAt(fila, 2) );
        inputDireccion.setText((String) Tabla.getValueAt(fila, 3) );
        inputSalario.setText( Tabla.getValueAt(fila, 4).toString());
        inputPoblacion.setText((String) Tabla.getValueAt(fila, 5) );
       
         
       
    }//GEN-LAST:event_TablaMouseClicked

    private void Eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar1MouseClicked
        // TODO add your handling code here:
       ControladorCamioneros cm = new ControladorCamioneros(Camioneros.this) ; 
       cm.eliminar();
       cm.listar(Tabla);
        
    }//GEN-LAST:event_Eliminar1MouseClicked

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar1ActionPerformed

    public JPanel getJpanel(){
        return Asignacion;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Camioneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Camioneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Camioneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Camioneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Camioneros().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Actualizar;
    public static javax.swing.JPanel Asignacion;
    public static javax.swing.JButton Asignar;
    public static javax.swing.JButton Consultar;
    public static javax.swing.JButton Crear;
    public static javax.swing.JButton Eliminar1;
    public javax.swing.JTable Tabla;
    public static javax.swing.JTextField inputCedula;
    public static javax.swing.JTextField inputDireccion;
    public static javax.swing.JTextField inputNombre;
    public static javax.swing.JTextField inputPoblacion;
    public static javax.swing.JTextField inputSalario;
    public static javax.swing.JTextField inputTelefono;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
