
package Vista.Paneles;


import Controlador.ControladorCamioneros;
import Controlador.ControladorCamiones;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author roy-j
 */
public class Camiones extends javax.swing.JFrame {
    
    

    public Camiones() {
        initComponents();
        ControladorCamiones cm = new ControladorCamiones(Camiones.this) ; 
        cm.listar(Tabla);

    }
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Asignacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        inputMatricula = new javax.swing.JTextField();
        Consultar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        inputTipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        inputPotencia = new javax.swing.JTextField();
        Modelo = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        inputModelo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Asignacion.setBackground(new java.awt.Color(255, 255, 255));
        Asignacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/car.png"))); // NOI18N
        Asignacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, -10, 140, 152));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel4.setText("Matricula");
        Asignacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        Asignacion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1020, 26));

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, 20));

        inputMatricula.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputMatricula.setToolTipText("");
        inputMatricula.setBorder(null);
        inputMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputMatriculaMousePressed(evt);
            }
        });
        inputMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMatriculaActionPerformed(evt);
            }
        });
        Asignacion.add(inputMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 30));

        Consultar.setBackground(new java.awt.Color(181, 223, 224));
        Consultar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Consultar.setText("Consultar");
        Consultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarMouseClicked(evt);
            }
        });
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        Asignacion.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 160, 30));

        Crear.setBackground(new java.awt.Color(181, 223, 224));
        Crear.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Crear.setText("Crear");
        Crear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        Asignacion.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 160, 30));

        Actualizar.setBackground(new java.awt.Color(181, 223, 224));
        Actualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        Asignacion.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 160, 30));

        Eliminar.setBackground(new java.awt.Color(181, 223, 224));
        Eliminar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        Asignacion.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 570, 160, 30));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        jLabel5.setText("Listado de Camiones");
        Asignacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 270, 40));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel6.setText("Tipo");
        Asignacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 150, 20));

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 190, 20));

        inputTipo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputTipo.setToolTipText("");
        inputTipo.setBorder(null);
        inputTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputTipoMousePressed(evt);
            }
        });
        inputTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTipoActionPerformed(evt);
            }
        });
        Asignacion.add(inputTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 210, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setText("Potencia");
        Asignacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 150, 20));

        jSeparator7.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 190, 20));

        inputPotencia.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputPotencia.setToolTipText("");
        inputPotencia.setBorder(null);
        inputPotencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputPotenciaMousePressed(evt);
            }
        });
        inputPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPotenciaActionPerformed(evt);
            }
        });
        Asignacion.add(inputPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 210, 30));

        Modelo.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        Modelo.setText("Modelo");
        Asignacion.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 150, 20));

        jSeparator8.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 190, 20));

        inputModelo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputModelo.setToolTipText("");
        inputModelo.setBorder(null);
        inputModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputModeloMousePressed(evt);
            }
        });
        inputModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputModeloActionPerformed(evt);
            }
        });
        Asignacion.add(inputModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 210, 30));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel11.setText("Administracion de Camiones");
        Asignacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 560, 40));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        Asignacion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 670, 280));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel8.setText("Datos del Camion");
        Asignacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();

        inputMatricula.setText(Tabla.getValueAt(fila, 0).toString());
        inputTipo.setText((String) Tabla.getValueAt(fila, 1));
        inputPotencia.setText((String) Tabla.getValueAt(fila, 2) );
        inputModelo.setText((String) Tabla.getValueAt(fila, 3) );
    }//GEN-LAST:event_TablaMouseClicked

    private void inputModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputModeloActionPerformed

    private void inputModeloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputModeloMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputModeloMousePressed

    private void inputPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPotenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPotenciaActionPerformed

    private void inputPotenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPotenciaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPotenciaMousePressed

    private void inputTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipoActionPerformed

    private void inputTipoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputTipoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipoMousePressed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        ControladorCamiones cm = new ControladorCamiones(Camiones.this) ;
        cm.eliminar();
        cm.listar(Tabla);
    }//GEN-LAST:event_EliminarMouseClicked

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed

    }//GEN-LAST:event_ActualizarActionPerformed

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked

        ControladorCamiones cm = new ControladorCamiones(Camiones.this) ;
        cm.actualizarCamion();
        cm.listar(Tabla);
    }//GEN-LAST:event_ActualizarMouseClicked

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearActionPerformed

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        ControladorCamiones cm = new ControladorCamiones(Camiones.this) ;
        cm.crear();
        cm.listar(Tabla);
    }//GEN-LAST:event_CrearMouseClicked

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarActionPerformed

    private void ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarMouseClicked
       ControladorCamiones cm = new ControladorCamiones(Camiones.this) ;
        cm.consultarCamion(Tabla);
    }//GEN-LAST:event_ConsultarMouseClicked

    private void inputMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMatriculaActionPerformed

    private void inputMatriculaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputMatriculaMousePressed
        if(inputMatricula.getText().equals("Placa")){
            inputMatricula.setText("");
            inputMatricula.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_inputMatriculaMousePressed

    public JPanel getJpanel(){
        return Asignacion;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Camiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Camiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Camiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Camiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Camiones().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JPanel Asignacion;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel Modelo;
    private javax.swing.JTable Tabla;
    public javax.swing.JTextField inputMatricula;
    public javax.swing.JTextField inputModelo;
    public javax.swing.JTextField inputPotencia;
    public javax.swing.JTextField inputTipo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
