package Vista.Paneles;


import Controlador.ControladorDetallesLlegada;
import Modelo.CambiaPanel;
import Modelo.DAO.ProvinciasDAO;
import Modelo.entidades.Provincia;
import static Vista.Menu.PanelPrincipal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author roy-j
 */
public class LlegadaPaquete extends javax.swing.JFrame {
    
    public LlegadaPaquete() {
        initComponents();
        ControladorDetallesLlegada cd = new ControladorDetallesLlegada(LlegadaPaquete.this);        
        cd.listar(Tabla);{
        cd.consultarPaquete(JPaquete);
        cd.consultarProvincia(JProvincia);
    }
    
        
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public void cambiarPanel(JPanel nuevoPanel) {
        new CambiaPanel(PanelPrincipal, nuevoPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Asignacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Consultar = new javax.swing.JButton();
        ReportarLlegada = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Eliminar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JPaquete = new javax.swing.JComboBox<>();
        JProvincia = new javax.swing.JComboBox<>();
        Codigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Fecha = new javax.swing.JTextField();
        Observaciones = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Asignacion.setBackground(new java.awt.Color(255, 255, 255));
        Asignacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/car.png"))); // NOI18N
        Asignacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 137, 152));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel4.setText("Codigo");
        Asignacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        Asignacion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1020, 26));

        Consultar.setBackground(new java.awt.Color(181, 223, 224));
        Consultar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Consultar.setText("Consultar");
        Consultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConsultarMouseEntered(evt);
            }
        });
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        Asignacion.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 160, 30));

        ReportarLlegada.setBackground(new java.awt.Color(181, 223, 224));
        ReportarLlegada.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        ReportarLlegada.setText("Reportar Llegada");
        ReportarLlegada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReportarLlegada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportarLlegadaMouseClicked(evt);
            }
        });
        ReportarLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportarLlegadaActionPerformed(evt);
            }
        });
        Asignacion.add(ReportarLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 190, 30));

        Actualizar.setBackground(new java.awt.Color(181, 223, 224));
        Actualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        Asignacion.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 160, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setText("Fecha");
        Asignacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 210, 20));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel11.setText("Administracion de P¨rovincias");
        Asignacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 560, 40));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        Asignacion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 850, 200));

        Eliminar1.setBackground(new java.awt.Color(181, 223, 224));
        Eliminar1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Eliminar1.setText("Eliminar");
        Eliminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar1MouseClicked(evt);
            }
        });
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });
        Asignacion.add(Eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 160, 30));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel13.setText("Datos de la provincia");
        Asignacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 270, 40));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        jLabel9.setText("Lista de llegada");
        Asignacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 160, 40));

        Asignacion.add(JPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 170, 30));

        Asignacion.add(JProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 170, 30));

        Codigo.setEditable(false);
        Codigo.setBackground(new java.awt.Color(204, 204, 204));
        Asignacion.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel5.setText("Ingresa el Paquete");
        Asignacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 210, 20));

        Fecha.setEditable(false);
        Asignacion.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 140, 30));
        Asignacion.add(Observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 190, 30));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel8.setText("Obsercaciones");
        Asignacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 210, 20));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel10.setText("Ingresa la Provincia");
        Asignacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarMouseClicked
          ControladorDetallesLlegada cd = new ControladorDetallesLlegada(LlegadaPaquete.this);        
            cd.consultarReporte(Tabla);

    }//GEN-LAST:event_ConsultarMouseClicked

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_ConsultarActionPerformed

    private void ReportarLlegadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportarLlegadaMouseClicked
        ControladorDetallesLlegada cd = new ControladorDetallesLlegada(LlegadaPaquete.this);  
        cd.crearReporteLlegada();
        cd.listar(Tabla);
    }//GEN-LAST:event_ReportarLlegadaMouseClicked

    private void ReportarLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportarLlegadaActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_ReportarLlegadaActionPerformed

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked
         ControladorDetallesLlegada cd = new ControladorDetallesLlegada(LlegadaPaquete.this);  
        cd.actualizarReporte();
        cd.listar(Tabla);
    }//GEN-LAST:event_ActualizarMouseClicked

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        
    }//GEN-LAST:event_ActualizarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        //TODO add your handling code here:
       int fila = Tabla.getSelectedRow();
        
        Codigo.setText(Tabla.getValueAt(fila, 0).toString());
        JPaquete.setSelectedItem(Tabla.getValueAt(fila, 1).toString());
        ProvinciasDAO sqlProvincias= new  ProvinciasDAO();
        ArrayList<Provincia> listaProvincias = sqlProvincias.obtenerTodos();//Crear un array para guardar lo obtenido de la funcionDAO
        int provinciaINT = Integer.parseInt(Tabla.getValueAt(fila, 2).toString());
        for (Provincia provincia : listaProvincias) { //Encontrar similitud con la informacion recogida y el SQL mediante DAO
            int codigo = provincia.getCodigo();
            if (codigo == provinciaINT) {
                JProvincia.setSelectedItem(provincia.getNombre());
            }
        }
        //JProvincia.setSelectedItem((String) Tabla.getValueAt(fila, 2));
        Fecha.setText((String) Tabla.getValueAt(fila, 3));
        Observaciones.setText((String) Tabla.getValueAt(fila, 4));
        

    }//GEN-LAST:event_TablaMouseClicked

    private void Eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar1MouseClicked
       ControladorDetallesLlegada cd = new ControladorDetallesLlegada(LlegadaPaquete.this);  
        cd.eliminar();
        cd.listar(Tabla);
    }//GEN-LAST:event_Eliminar1MouseClicked

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar1ActionPerformed

    private void ConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarMouseEntered
    
    public JPanel getJpanel() {
        return Asignacion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LlegadaPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LlegadaPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LlegadaPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LlegadaPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LlegadaPaquete().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Actualizar;
    public static javax.swing.JPanel Asignacion;
    public javax.swing.JTextField Codigo;
    public static javax.swing.JButton Consultar;
    public static javax.swing.JButton Eliminar1;
    public javax.swing.JTextField Fecha;
    public javax.swing.JComboBox<String> JPaquete;
    public javax.swing.JComboBox<String> JProvincia;
    public javax.swing.JTextField Observaciones;
    public static javax.swing.JButton ReportarLlegada;
    public javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
