package Vista.Paneles;

import Controlador.ControladorAsignarCamion;
import Controlador.ControladorCamioneros;
import Controlador.ControladorPaquetes;
import Modelo.CambiaPanel;
import Modelo.entidades.Camionero;
import Vista.Menu;
import static Vista.Menu.PanelPrincipal;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author roy-j
 */
public class Paquetes extends javax.swing.JFrame {
    
    public Paquetes() {
        initComponents();
        ControladorPaquetes pq = new ControladorPaquetes(Paquetes.this);        
        pq.listar(Tabla);
        JcCamioneros.setVisible(false);
        txtAsgn.setVisible(false);
        
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public void cambiarPanel(JPanel nuevoPanel) {
        new CambiaPanel(PanelPrincipal, nuevoPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Asignacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        inputCodigo = new javax.swing.JTextField();
        Consultar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Asignar = new javax.swing.JButton();
        txtAsgn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        inputDescripcion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        inputDestinatario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        inputDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Eliminar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JcCamioneros = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Asignacion.setBackground(new java.awt.Color(255, 255, 255));
        Asignacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/car.png"))); // NOI18N
        Asignacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 137, 152));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel4.setText("Codigo");
        Asignacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        Asignacion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1020, 26));

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 250, 20));

        inputCodigo.setEditable(false);
        inputCodigo.setBackground(new java.awt.Color(204, 204, 204));
        inputCodigo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputCodigo.setToolTipText("");
        inputCodigo.setBorder(null);
        inputCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputCodigoMousePressed(evt);
            }
        });
        inputCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCodigoActionPerformed(evt);
            }
        });
        Asignacion.add(inputCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 270, 30));

        Consultar.setBackground(new java.awt.Color(181, 223, 224));
        Consultar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Consultar.setText("Consultar");
        Consultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarMouseClicked(evt);
            }
        });
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        Asignacion.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 160, 30));

        Crear.setBackground(new java.awt.Color(181, 223, 224));
        Crear.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Crear.setText("Crear");
        Crear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        Asignacion.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 160, 30));

        Actualizar.setBackground(new java.awt.Color(181, 223, 224));
        Actualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        Asignacion.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 160, 30));

        Asignar.setBackground(new java.awt.Color(181, 223, 224));
        Asignar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Asignar.setText("Asignar Camionero");
        Asignar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Asignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AsignarMouseClicked(evt);
            }
        });
        Asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarActionPerformed(evt);
            }
        });
        Asignacion.add(Asignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 190, 30));

        txtAsgn.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        txtAsgn.setText("Seleciona el Camionero a Asignar");
        Asignacion.add(txtAsgn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 280, 40));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel6.setText("Descripcion");
        Asignacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 210, 20));

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, 20));

        inputDescripcion.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputDescripcion.setToolTipText("");
        inputDescripcion.setBorder(null);
        inputDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputDescripcionMousePressed(evt);
            }
        });
        inputDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDescripcionActionPerformed(evt);
            }
        });
        Asignacion.add(inputDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 270, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setText("Destinatario");
        Asignacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 20));

        jSeparator7.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 250, 20));

        inputDestinatario.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputDestinatario.setToolTipText("");
        inputDestinatario.setBorder(null);
        inputDestinatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputDestinatarioMousePressed(evt);
            }
        });
        inputDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDestinatarioActionPerformed(evt);
            }
        });
        Asignacion.add(inputDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 270, 30));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel8.setText("Direccion Destinatario");
        Asignacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 210, 20));

        jSeparator8.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 250, 20));

        inputDireccion.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputDireccion.setToolTipText("");
        inputDireccion.setBorder(null);
        inputDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputDireccionMousePressed(evt);
            }
        });
        inputDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDireccionActionPerformed(evt);
            }
        });
        Asignacion.add(inputDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 270, 30));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel11.setText("Administracion de Paquetes");
        Asignacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 560, 40));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        Asignacion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 650, 330));

        Eliminar1.setBackground(new java.awt.Color(181, 223, 224));
        Eliminar1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Eliminar1.setText("Eliminar");
        Eliminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar1MouseClicked(evt);
            }
        });
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });
        Asignacion.add(Eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 570, 160, 30));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel13.setText("Datos del Paquete");
        Asignacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 220, 40));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        jLabel9.setText("Lista de Paquetes");
        Asignacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 220, 40));

        JcCamioneros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JcCamioneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcCamionerosActionPerformed(evt);
            }
        });
        Asignacion.add(JcCamioneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 250, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Asignacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCodigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputCodigoMousePressed
        if (inputCodigo.getText().equals("Placa")) {
            inputCodigo.setText("");
            inputCodigo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_inputCodigoMousePressed

    private void inputCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodigoActionPerformed

    private void ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarMouseClicked
        ControladorPaquetes pq = new ControladorPaquetes(Paquetes.this);        
        pq.consultarPaquete(Tabla);
    }//GEN-LAST:event_ConsultarMouseClicked

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_ConsultarActionPerformed

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        ControladorPaquetes pq = new ControladorPaquetes(Paquetes.this);        
        pq.crearCamionero();
        pq.listar(Tabla);
    }//GEN-LAST:event_CrearMouseClicked

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_CrearActionPerformed

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked
        ControladorPaquetes pq = new ControladorPaquetes(Paquetes.this);        
        pq.actualizarPaquete();
        pq.listar(Tabla);
    }//GEN-LAST:event_ActualizarMouseClicked

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        
    }//GEN-LAST:event_ActualizarActionPerformed

    private void AsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AsignarMouseClicked
        JcCamioneros.setVisible(true);
        txtAsgn.setVisible(true);
        ControladorPaquetes pq = new ControladorPaquetes(Paquetes.this); 
        pq.consultarCambioneroNombre(JcCamioneros);
        
    }//GEN-LAST:event_AsignarMouseClicked

    private void AsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsignarActionPerformed

    private void inputDestinatarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDestinatarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDestinatarioMousePressed

    private void inputDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDestinatarioActionPerformed

    private void inputDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDireccionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDireccionMousePressed

    private void inputDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDireccionActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
        
        inputCodigo.setText(Tabla.getValueAt(fila, 0).toString());
        inputDestinatario.setText((String) Tabla.getValueAt(fila, 1));
        inputDireccion.setText((String) Tabla.getValueAt(fila, 2));
        inputDescripcion.setText((String) Tabla.getValueAt(fila, 3));
        

    }//GEN-LAST:event_TablaMouseClicked

    private void Eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar1MouseClicked
        ControladorPaquetes pq = new ControladorPaquetes(Paquetes.this);        
        pq.eliminar();
        pq.listar(Tabla);
    }//GEN-LAST:event_Eliminar1MouseClicked

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar1ActionPerformed

    private void inputDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDescripcionActionPerformed

    private void inputDescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputDescripcionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDescripcionMousePressed

    private void JcCamionerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcCamionerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcCamionerosActionPerformed
    
    public JPanel getJpanel() {
        return Asignacion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paquetes().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Actualizar;
    public static javax.swing.JPanel Asignacion;
    public static javax.swing.JButton Asignar;
    public static javax.swing.JButton Consultar;
    public static javax.swing.JButton Crear;
    public static javax.swing.JButton Eliminar1;
    public javax.swing.JComboBox<String> JcCamioneros;
    public javax.swing.JTable Tabla;
    public javax.swing.JTextField inputCodigo;
    public javax.swing.JTextField inputDescripcion;
    public javax.swing.JTextField inputDestinatario;
    public javax.swing.JTextField inputDireccion;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel txtAsgn;
    // End of variables declaration//GEN-END:variables
}
