package Vista.Paneles;

import Controlador.ControladorAsignarCamion;
import Controlador.ControladorCamioneros;
import Controlador.ControladorPaquetes;
import Controlador.ControladorProvincias;
import Modelo.CambiaPanel;
import Modelo.entidades.Camionero;
import Vista.Menu;
import static Vista.Menu.PanelPrincipal;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author roy-j
 */
public class Provincias extends javax.swing.JFrame {
    
    public Provincias() {
        initComponents();
        ControladorProvincias cp = new ControladorProvincias(Provincias.this);        
        cp.listar(Tabla);
    
        
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public void cambiarPanel(JPanel nuevoPanel) {
        new CambiaPanel(PanelPrincipal, nuevoPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Asignacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        inputCodigo = new javax.swing.JTextField();
        Consultar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        LlegadaPaquete = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        inputProvincia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Eliminar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Asignacion.setBackground(new java.awt.Color(255, 255, 255));
        Asignacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/car.png"))); // NOI18N
        Asignacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 137, 152));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel4.setText("Codigo");
        Asignacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        Asignacion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1020, 26));

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 250, 20));

        inputCodigo.setEditable(false);
        inputCodigo.setBackground(new java.awt.Color(204, 204, 204));
        inputCodigo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputCodigo.setToolTipText("");
        inputCodigo.setBorder(null);
        inputCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputCodigoMousePressed(evt);
            }
        });
        inputCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCodigoActionPerformed(evt);
            }
        });
        Asignacion.add(inputCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 270, 30));

        Consultar.setBackground(new java.awt.Color(181, 223, 224));
        Consultar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Consultar.setText("Consultar");
        Consultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarMouseClicked(evt);
            }
        });
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        Asignacion.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 160, 30));

        Crear.setBackground(new java.awt.Color(181, 223, 224));
        Crear.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Crear.setText("Crear");
        Crear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        Asignacion.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 160, 30));

        Actualizar.setBackground(new java.awt.Color(181, 223, 224));
        Actualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        Asignacion.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 160, 30));

        LlegadaPaquete.setBackground(new java.awt.Color(181, 223, 224));
        LlegadaPaquete.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        LlegadaPaquete.setText("Llegada Paquete");
        LlegadaPaquete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LlegadaPaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LlegadaPaqueteMouseClicked(evt);
            }
        });
        LlegadaPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlegadaPaqueteActionPerformed(evt);
            }
        });
        Asignacion.add(LlegadaPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 190, 30));

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 250, 20));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setText("Nombre Provincia");
        Asignacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 210, 20));

        inputProvincia.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        inputProvincia.setToolTipText("");
        inputProvincia.setBorder(null);
        inputProvincia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputProvinciaMousePressed(evt);
            }
        });
        inputProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputProvinciaActionPerformed(evt);
            }
        });
        Asignacion.add(inputProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 270, 30));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel11.setText("Administracion de P¨rovincias");
        Asignacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 560, 40));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        Asignacion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 330, 330));

        Eliminar1.setBackground(new java.awt.Color(181, 223, 224));
        Eliminar1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Eliminar1.setText("Eliminar");
        Eliminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar1MouseClicked(evt);
            }
        });
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });
        Asignacion.add(Eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 570, 160, 30));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel13.setText("Datos de la provincia");
        Asignacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 270, 40));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        jLabel9.setText("Lista de Provincias");
        Asignacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCodigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputCodigoMousePressed
   
    }//GEN-LAST:event_inputCodigoMousePressed

    private void inputCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodigoActionPerformed

    private void ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarMouseClicked
        ControladorProvincias cp = new ControladorProvincias(Provincias.this);        
        cp.consultarProvincia(Tabla);

    }//GEN-LAST:event_ConsultarMouseClicked

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_ConsultarActionPerformed

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        ControladorProvincias cp = new ControladorProvincias(Provincias.this);        
        cp.crearProvincia();
        cp.listar(Tabla);
    }//GEN-LAST:event_CrearMouseClicked

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_CrearActionPerformed

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked
        ControladorProvincias cp = new ControladorProvincias(Provincias.this);        
        cp.actualizarProvincia();
        cp.listar(Tabla);
    }//GEN-LAST:event_ActualizarMouseClicked

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        
    }//GEN-LAST:event_ActualizarActionPerformed

    private void LlegadaPaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LlegadaPaqueteMouseClicked
        LlegadaPaquete llg = new LlegadaPaquete();
        cambiarPanel(llg.getJpanel());
        
    }//GEN-LAST:event_LlegadaPaqueteMouseClicked

    private void LlegadaPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlegadaPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LlegadaPaqueteActionPerformed

    private void inputProvinciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputProvinciaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputProvinciaMousePressed

    private void inputProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputProvinciaActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
        
        inputCodigo.setText(Tabla.getValueAt(fila, 0).toString());
        inputProvincia.setText((String) Tabla.getValueAt(fila, 1));
        

    }//GEN-LAST:event_TablaMouseClicked

    private void Eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar1MouseClicked
        ControladorProvincias cp = new ControladorProvincias(Provincias.this);        
        cp.eliminar();
        cp.listar(Tabla);
    }//GEN-LAST:event_Eliminar1MouseClicked

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar1ActionPerformed
    
    public JPanel getJpanel() {
        return Asignacion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Provincias().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Actualizar;
    public static javax.swing.JPanel Asignacion;
    public static javax.swing.JButton Consultar;
    public static javax.swing.JButton Crear;
    public static javax.swing.JButton Eliminar1;
    public static javax.swing.JButton LlegadaPaquete;
    public javax.swing.JTable Tabla;
    public javax.swing.JTextField inputCodigo;
    public javax.swing.JTextField inputProvincia;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
